<?php

/*
 * DB connection script for Editor
 * Automatically generated by http://editor.datatables.net/generator
 */

error_reporting(E_ALL);
ini_set('display_errors', '1');

/*
 * Edit the following with your database connection options
 */
$sql_details = array(
	"type" => "Mysql",
	"user" => "anytv_ron",
	"pass" => "09213972063",
	"host" => "localhost",
	"port" => "",
	"db"   => "anytv_gbase"
);

