
/*
 * Editor client script for DB table ginfo
 * Automatically generated by http://editor.datatables.net/generator
 */

(function($){

$(document).ready(function() {
	var editor = new $.fn.dataTable.Editor( {
		"ajaxUrl": "php/table.ginfo.php",
		"domTable": "#ginfo",
		"fields": [
			{
				"label": "Name",
				"name": "game_name",
				"type": "text"
			},
			{
				"label": "AKA",
				"name": "game_alias",
				"type": "text"
			},
			{
				"label": "Site",
				"name": "game_site",
				"type": "text"
			},
			{
				"label": "Video ID",
				"name": "game_video",
				"type": "text"
			},
			{
				"label": "Publisher",
				"name": "game_publisher",
				"type": "text"
			},
			{
				"label": "PVP",
				"name": "game_genre",
				"type": "checkbox",
				"ipOpts": [
					{
						"label": "Yes ",
						"value": "Yes "
					},
					{
						"label": " No",
						"value": " No"
					}
				],
				"separator": "|"
			},
			{
				"label": "Genre",
				"name": "game_genre",
				"type": "checkbox",
				"ipOpts": [
					{
						"label": "Battle Arena ",
						"value": "Battle Arena "
					},
					{
						"label": " Role-Playing ",
						"value": " Role-Playing "
					},
					{
						"label": " First-Person Shooter ",
						"value": " First-Person Shooter "
					},
					{
						"label": " Real-Time Strategy ",
						"value": " Real-Time Strategy "
					},
					{
						"label": " Turn-Based Strategy ",
						"value": " Turn-Based Strategy "
					},
					{
						"label": " Racing ",
						"value": " Racing "
					},
					{
						"label": " Casual ",
						"value": " Casual "
					},
					{
						"label": " Sports ",
						"value": " Sports "
					},
					{
						"label": " Simulation",
						"value": " Simulation"
					}
				],
				"separator": "|"
			},
			{
				"label": "Processor",
				"name": "game_processor",
				"type": "text"
			},
			{
				"label": "Videocard",
				"name": "game_videocard",
				"type": "text"
			},
			{
				"label": "HDD",
				"name": "game_harddrive",
				"type": "text"
			},
			{
				"label": "RAM",
				"name": "game_ram",
				"type": "text"
			},
			{
				"label": "Added by:",
				"name": "game_addedby",
				"type": "text"
			}
		]
	} );

	$('#ginfo').dataTable( {
		"sDom": "Tfrtip",
		"sAjaxSource": "php/table.ginfo.php",
		"aoColumns": [
			{
				"mData": "game_name"
			},
			{
				"mData": "game_alias"
			},
			{
				"mData": "game_site"
			},
			{
				"mData": "game_video"
			},
			{
				"mData": "game_publisher"
			},
			{
				"mData": "game_genre"
			},
			{
				"mData": "game_genre"
			},
			{
				"mData": "game_processor"
			},
			{
				"mData": "game_videocard"
			},
			{
				"mData": "game_harddrive"
			},
			{
				"mData": "game_ram"
			},
			{
				"mData": "game_addedby"
			}
		],
		"oTableTools": {
			"sRowSelect": "multi",
			"aButtons": [
				{ "sExtends": "editor_create", "editor": editor },
				{ "sExtends": "editor_edit",   "editor": editor },
				{ "sExtends": "editor_remove", "editor": editor }
			]
		}
	} );
} );

}(jQuery));

