<?php

/*
 * Editor server script for DB table gen_info
 * Automatically generated by http://editor.datatables.net/generator
 */

// DataTables PHP library
include( "lib/DataTables.php" );

// Alias Editor classes so they are easy to use
use
	DataTables\Editor,
	DataTables\Editor\Field,
	DataTables\Editor\Format,
	DataTables\Editor\Join,
	DataTables\Editor\Validate;


// Build our Editor instance and process the data coming from _POST
Editor::inst( $db, 'gen_info' )
	->fields(
		Field::inst( 'game_name' )
			->validator( 'Validate::required' ),
		Field::inst( 'game_alias' )
			->validator( 'Validate::required' ),
		Field::inst( 'game_site' ),
		Field::inst( 'game_publisher' ),
		Field::inst( 'game_pvp' ),
		Field::inst( 'game_genre' ),
		Field::inst( 'game_os' ),
		Field::inst( 'game_processor' ),
		Field::inst( 'game_videocard' ),
		Field::inst( 'game_ram' ),
		Field::inst( 'game_harddrive' ),
		Field::inst( 'game_addedby' )
			->validator( 'Validate::required' ),
		Field::inst( 'game_dateadded' )
			->validator( 'Validate::dateFormat_required', 'D, j M y' )
			->getFormatter( 'Format::date_sql_to_format', 'D, j M y' )
			->setFormatter( 'Format::date_format_to_sql', 'D, j M y' )
	)
	->process( $_POST )
	->json();

