
-- 
-- Editor server script for DB table gen_info
-- Automatically generated by http://editor.datatables.net/generator
-- 

CREATE TABLE `gen_info` (
	`id` int(10) NOT NULL auto_increment,
	`game_name` varchar(255) default NULL,
	`game_alias` varchar(255) default NULL,
	`game_site` varchar(255) default NULL,
	`game_video` varchar(255) default NULL,
	`game_publisher` varchar(255) default NULL,
	`game_pvp` varchar(255) default NULL,
	`game_genre` varchar(255) default NULL,
	`game_os` varchar(255) default NULL,
	`game_processor` varchar(255) default NULL,
	`game_videocard` varchar(255) default NULL,
	`game_harddisk` varchar(255) default NULL,
	`game_ram` varchar(255) default NULL,
	`game_addedby` varchar(255) default NULL,
	`game_dateaddedd` timestamp,
	PRIMARY KEY  (`id`)
);

